# 1. 数据集有关参数
dataset_name: 'AliExpress_NL' # choices=['AliExpress_NL', 'AliExpress_ES', 'AliExpress_FR', 'AliExpress_US']
dataset_path: './data/'

# 2. 模型选择。包括模型内部的参数选择。
model_name: 'ple' # choices=['singletask', 'sharedbottom', 'omoe', 'mmoe', 'ple', 'aitm', 'metaheac']
expert_num: 8
embed_dim: 128
weights: 

# 3. 基础loss的选择

# categorical_loss: AUCMLoss
categorical_loss: BCELoss
numeric_loss: 

# 3.1离散型分类任务
# 3.1.1普通分布
# criterion = torch.nn.BCELoss()
# 3.1.2类别不平衡
# 3.2连续型回归任务
# criterion = torch.nn.MSELoss()

# 4. 优化器
# 4.1 基础优化器
# optimizer_name: PESG
optimizer_name: Adam
learning_rate: 1.0e-3
weight_decay: 1.0e-6


# 5. 多任务平衡器选择
do_balance: false
balancer_name: MetaBalance

# 6. 训练器的选择
# trainer: default  # balance_train, meta_train
# 不允许选择，需要自动推导。


# 7. 训练过程有关参数
# 训练
device: '0,1,2,3'
save_dir: 'runs/NL_basic'
save_epoch: 4

# 经典参数
max_epochs: 50
batch_size: 2048

# early stop
patience: 10
min_delta: 0
cumulative_delta: false

